### ISSUE TITLE
这是成功了，还是失败了

### ISSUE THREAD

**Issue by openMJJ** [doveppp/linuxdo-checkin#1]
另外，佬这个可以支持多个用户吗？

python main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:3).9.19/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.19/x6[4](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:4)/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib
    USERNAME: ***
    PASSWORD: ***
  
Traceback (most recent call last):
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 86, in <module>
    l.run()
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line [5](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:5)1, in run
    if not self.login():
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 25, in login
    self.page.click(".header-buttons .d-button-label")
  File "/opt/hostedtoolcache/Python/3.9.19/x[6](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:6)4/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9492, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py", line [7](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:7)53, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 4[8](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:8)8, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.[9](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:9).19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 5[13](https://github.com/openMJJ/linuxdo-checkin/actions/runs/9257466192/job/25465643091#step:5:13), in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded.
Call log:
waiting for locator(".header-buttons .d-button-label")

Error: Process completed with exit code 1.

**Comment by doveppp** [comment]
失败了
这两天网站正在变动，等稳定了再修


不支持多用户，不提倡用这个脚本批量签到

**Comment by doveppp** [comment]
网站稳定下来了 不用修，还可以正常用

**Comment by openMJJ** [comment]
谢谢。
