### ISSUE TITLE
playwright._impl._errors.TargetClosedError: BrowserContext.new_page: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by doveppp** [doveppp/linuxdo-checkin#10]
使用Firefox时部分人会出现以下问题：
```
Traceback (most recent call last):
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 127, in <module>
    l = LinuxDoBrowser()
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 20, in __init__
    self.page = self.context.new_page()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 12323, in new_page
    return mapping.from_impl(self._sync(self._impl_obj.new_page()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 11[5](https://github.com/it985/linuxdo-checkin/actions/runs/12452136342/job/34760769058#step:5:5), in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x[6](https://github.com/it985/linuxdo-checkin/actions/runs/12452136342/job/34760769058#step:5:6)4/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 294, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/opt/hostedtoolcache/Python/3.[9](https://github.com/it985/linuxdo-checkin/actions/runs/12452136342/job/34760769058#step:5:9).19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 5[13](https://github.com/it985/linuxdo-checkin/actions/runs/12452136342/job/34760769058#step:5:14), in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: BrowserContext.new_page: Target page, context or browser has been closed
```

**Comment by neeko8** [comment]
这个错误怎么解决呢

**Comment by it985** [comment]
切换dev分支依然报错，[详见](https://github.com/it985/linuxdo-checkin/actions/runs/12452855230/job/34762320416)

**Comment by dqzboy** [comment]
同步最新代码后 还是报错
![image](https://github.com/user-attachments/assets/f16d6287-ce47-4ccb-b112-fe15d97c3b83)

**Comment by doveppp** [comment]
再试试dev分支

**Comment by dqzboy** [comment]
> 再试试dev分支

Traceback (most recent call last):
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 132, in <module>
    l.run()
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 86, in run
    if not self.login():
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 29, in login
    self.page.click(".login-button .d-button-label")
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9492, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 1[15](https://github.com/dqzboy/linuxdo-checkin/actions/runs/12462113761/job/34782584445#step:5:16), in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py", line 753, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.[19](https://github.com/dqzboy/linuxdo-checkin/actions/runs/12462113761/job/34782584445#step:5:20)/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded.
Call log:
waiting for locator(".login-button .d-button-label")
Error: Process completed with exit code 1.

还是报错

**Comment by it985** [comment]
dev分支，最新commit，[报错](https://github.com/it985/linuxdo-checkin/actions/runs/12462947369/job/34784591115)
```
Run python main.py
2024-12-23 07:21:32.179 | INFO     | __main__:login:28 - Login
2024-12-23 07:21:48.520 | ERROR    | __main__:login:39 - Login failed
```
用户名密码全对

**Comment by doveppp** [comment]
> > 再试试dev分支
> 
> Traceback (most recent call last): File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 132, in l.run() File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 86, in run if not self.login(): File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 29, in login self.page.click(".login-button .d-button-label") File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9492, in click self._sync( File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 1[15](https://github.com/dqzboy/linuxdo-checkin/actions/runs/12462113761/job/34782584445#step:5:16), in _sync return task.result() File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py", line 753, in click return await self._main_frame.click(**locals_to_params(locals())) File "/opt/hostedtoolcache/Python/3.9.[19](https://github.com/dqzboy/linuxdo-checkin/actions/runs/12462113761/job/34782584445#step:5:20)/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 488, in click await self._channel.send("click", locals_to_params(locals())) File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send return await self._connection.wrap_api_call( File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded. Call log: waiting for locator(".login-button .d-button-label") Error: Process completed with exit code 1.
> 
> 还是报错

我看你最新的一次正常了，更改了什么？

**Comment by dqzboy** [comment]
没正常，就修改了daily-check-in.yml和main.py
![image](https://github.com/user-attachments/assets/a8a38b1c-e63b-4ebf-84ac-7de993d18c3c)

**Comment by Liaoyang985** [comment]
现在最新的是dev还是main

**Comment by Liaoyang985** [comment]
> dev最新，可以先试试main，不行的话换成dev

# 发送 Telegram 成功通知
      - name: Send Telegram Notification
        if: ${{ success() }}  # 只有当执行成功时发送通知
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_USERID }} \
          -d text="LINUX DO每日签到成功完成"

      # 发送失败通知（如果脚本执行失败）
      - name: Send Failure Notification
        if: ${{ failure() }}  # 只有当执行失败时发送失败通知
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_USERID }} \
          -d text="LINUX DO每日签到失败，请检查日志！"



可以在yml加tg通知

**Comment by dqzboy** [comment]
dev分支可以了 main分支失败

**Comment by doveppp** [comment]
此问题关闭，另：
tg通知已加

**Comment by dqzboy** [comment]
```log
Traceback (most recent call last):
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 132, in <module>
    l.run()
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 88, in run
    self.click_topic()
  File "/home/runner/work/linuxdo-checkin/linuxdo-checkin/main.py", line 51, in click_topic
    page.goto(HOME_URL + topic.get_attribute("href"))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8667, in goto
    self._sync(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py", line 500, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
navigating to "https://linux.do//t/topic/302219", waiting until "load"
```

今天又不行啦

**Comment by dqzboy** [comment]
手动执行成功了 是不是现在可以加上重试机制

**Comment by Liaoyang985** [comment]
用最新main分支

**Comment by dqzboy** [comment]
就是最新的代码

**Comment by Liaoyang985** [comment]
你把库重新复刻布置运行，我的没有问题

**Comment by dqzboy** [comment]
已经重新同步，看日志是可以点赞和查看帖子，但是最后就报错，等明天再看看吧
![image](https://github.com/user-attachments/assets/a5cdab3f-6d3c-438a-bc5e-b4f4357417a0)
